name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'default_logging/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'default_logging/**'
      - 'tests/**'
      - 'pyproject.toml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry==2.1.3

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest