name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'default_logging/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    types: [opened, reopened]
    branches:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      ref: ${{ github.ref }}